services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mpl_ulab_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    restart: unless-stopped
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
