SELECT
    BOOK.ID AS ID_B,
    BOOK.TITLE AS TITLE_B,
    BOOK.AUTHOR AS AUTHOR_B,
    BOOK.PAGE_COUNT AS PAGE_COUNT_B,
    BOOK.USER_ID AS USER_ID_B,
    PERSON.ID AS ID_P,
    PERSON.FULL_NAME AS FULL_NAME_P,
    PERSON.TITLE AS TITLE_P,
    PERSON.AGE AS AGE_P
FROM BOOK
LEFT JOIN
     PERSON ON BOOK.USER_ID = PERSON.ID
WHERE BOOK.ID = ?