swagger-api:
  version: "1.0"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mpl_ulab_db
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8091
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, info