CREATE TABLE ulab_edu.book
(
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(50) NOT NULL,
    author      VARCHAR(50) NOT NULL,
    page_count  BIGINT      NOT NULL,
    person_id   BIGINT      NOT NULL,
    CONSTRAINT pk_ulab_edu_book_id PRIMARY KEY (id)
);

COMMENT ON TABLE ulab_edu.book IS 'Used for storing books';
COMMENT ON COLUMN ulab_edu.book.id IS 'Book ID';
COMMENT ON COLUMN ulab_edu.book.person_id IS 'User ID';
COMMENT ON COLUMN ulab_edu.book.title IS 'Title';
COMMENT ON COLUMN ulab_edu.book.author IS 'Author';
COMMENT ON COLUMN ulab_edu.book.page_count IS 'Number of pages';

