CREATE SCHEMA ulab_edu;

CREATE TABLE ulab_edu.person
(
    id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(50)   NOT NULL,
    title     VARCHAR(50)   NOT NULL,
    age       INTEGER       NOT NULL,
    CONSTRAINT pk_ulab_edu_person_id PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_ulab_edu_person_title ON ulab_edu.person (title);

COMMENT ON TABLE ulab_edu.person IS 'Used for storing users';
COMMENT ON COLUMN ulab_edu.person.id IS 'User ID';
COMMENT ON COLUMN ulab_edu.person.full_name IS 'Full name';
COMMENT ON COLUMN ulab_edu.person.title IS 'Position';
COMMENT ON COLUMN ulab_edu.person.age IS 'Age';
